// <auto-generated />
using System;
using HotChocolate.EFCore.OwnedEntityError;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HotChoclate.EFCore.OwnedEntityError.Migrations
{
    [DbContext(typeof(HotContext))]
    partial class HotContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("HotChocolate.EFCore.OwnedEntityError.Shipment", b =>
                {
                    b.Property<Guid>("ShipmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.HasKey("ShipmentId");

                    b.ToTable("Shipments", (string)null);
                });

            modelBuilder.Entity("HotChocolate.EFCore.OwnedEntityError.Shipment", b =>
                {
                    b.OwnsOne("HotChocolate.EFCore.OwnedEntityError.Address", "Consignor", b1 =>
                        {
                            b1.Property<Guid>("ShipmentId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("AddressLine1")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("ShipmentId");

                            b1.ToTable("Shipments");

                            b1.WithOwner()
                                .HasForeignKey("ShipmentId");
                        });

                    b.Navigation("Consignor")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
